#ifndef __BME280_TYPES_H__
#define __BME280_TYPES_H__

#include "asserts.h"

typedef enum PACKED {
    BME208_REGISTER_ADDRESS_TEMPERATURE_CALIBRATION_PARAMETERS_T1 = 0x08,
    BME208_REGISTER_ADDRESS_PRESSURE_CALIBRATION_PARAMETERS_P1 = 0x0E,
    BME208_REGISTER_ADDRESS_HUMIDITY_CALIBRATION_PARAMETERS_H1 = 0x21,
    BME208_REGISTER_ADDRESS_HUMIDITY_CALIBRATION_PARAMETERS_H2 = 0x61,
    BME280_REGISTER_ADDRESS_ID = 0x50,
    BME280_REGISTER_ADDRESS_CTRL_HUMIDITY = 0x72,
    BME280_REGISTER_ADDRESS_CTRL_MEASUREMENT = 0x74,
    BME280_REGISTER_ADDRESS_READOUT_ALL_MEASUREMENTS = 0x77,
    BME280_REGISTER_ADDRESS_READOUT_PRESSURE_MSB = 0x77,
    BME280_REGISTER_ADDRESS_READOUT_TEMPERATURE_MSB = 0x7A,
    BME280_REGISTER_ADDRESS_READOUT_HUMIDITY_MSB = 0x7D,
} bme280_register_address_t;
ASSERT(sizeof(bme280_register_address_t) == 1);

#define BME280_ID (0x60)

#define BME280_CTRL_HUMIDITY_OVERSAMPLING_X1 (0b001)
#define BME280_CTRL_HUMIDITY_OVERSAMPLING_POS (0)
#define BME280_CTRL_MEASUREMENT_TEMPERATURE_OVERSAMPLING_X1 (0b001)
#define BME280_CTRL_MEASUREMENT_TEMPERATURE_OVERSAMPLING_POS (5)
#define BME280_CTRL_MEASUREMENT_PRESSURE_OVERSAMPLING_X1 (0b001)
#define BME280_CTRL_MEASUREMENT_PRESSURE_OVERSAMPLING_POS (2)
#define BME280_CTRL_MEASUREMENT_MODE_NORMAL (0b11)
#define BME280_CTRL_MEASUREMENT_MODE_POS (0)


#define BME280_PRESSURE_READOUT_RAW_SIZE_BYTES (3)
#define BME280_TEMPERATURE_READOUT_RAW_SIZE_BYTES (3)
#define BME280_HUMIDITY_READOUT_RAW_SIZE_BYTES (2)

#define BME280_ALL_READOUT_RAW_SIZE_BYTES ( \
    BME280_PRESSURE_READOUT_RAW_SIZE_BYTES \
        + BME280_TEMPERATURE_READOUT_RAW_SIZE_BYTES \
        + BME280_HUMIDITY_READOUT_RAW_SIZE_BYTES)

#endif // !__BME280_TYPES_H__